audio on killing enemy slash effect
3Pixel-Organization/Team-4 pull request #24
Opened 2021-05-29 04:53 UTC by avin77

commit to change audio and adding level01 copy  of the scene
//changes
-volume to play on killing enemy
-Audio Scriptable object slider for volume

2021-05-30 20:03 UTC, lolmanQ approved these changes
Approve

2021-05-30 20:15 UTC, lolmanQ requested changes
Fix this pls

2021-05-30 20:15 UTC, lolmanQ commented on Assets/Scripts/SoundSystem/AudioDataSO.cs
> +			audioSource.volume = volSlide;
You need to add this when the audio firsts gets set, otherwise it will only set the volume when the audio is played a second time

2021-05-31 05:13 UTC, avin77 commented
I will check

On Mon, 31 May, 2021, 1:45 am Elias, ***@***.***> wrote:

> ***@***.***Q* requested changes on this pull request.
>
> Fix this pls
> ------------------------------
>
> In Assets/Scripts/SoundSystem/AudioDataSO.cs
> <https://github.com/3Pixel-Organization/Team-4/pull/24#discussion_r642122692>
> :
>
> >
>  	public void Play()
>  	{
>  		if(gameObject != null && audioSource != null)
>  		{
>  			audioSource.Stop();
> +			audioSource.volume = volSlide;
>
> You need to add this when the audio firsts gets set, otherwise it will
> only set the volume when the audio is played a second time
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/3Pixel-Organization/Team-4/pull/24#pullrequestreview-671860775>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFZZEUCIJDD2TNP6X7M7ULTQKMFDANCNFSM45X424QA>
> .
>

2021-06-01 08:10 UTC, lolmanQ approved these changes
Good you can now merge

2021-06-01 08:17 UTC, merged